version: "3.8"

services:
  redis:
    image: redis:6.2.4
    container_name: redis
    command: redis-server --requirepass redis
    cap_add:
      - SYS_RESOURCE
    expose:
      - 6379
    ports:
      - 16379:6379
    networks:
      - redis-database
  app:
    depends_on:
      - redis
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - 18080:8080
    environment:
      spring.redis.host: "redis"
      spring.redis.port: "6379"
      spring.redis.password: "redis"
    stdin_open: true
    tty: true
    networks:
      - redis-database
networks:
  redis-database:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16