apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: my-redis-enterprise-db
spec:
  memorySize: 100MB
  replication: true
  persistence: snapshotEvery1Hour
  shardCount: 2
  evictionPolicy: allkeys-lru