apiVersion: v1
kind: Service
metadata:
  name: redis-dbaas-ext-rec-ui
  namespace: redis-dbaas
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: redis-enterprise
    redis.io/cluster: rec
    redis.io/role: node
    redis.io/role-master: "1"
  sessionAffinity: None
